### What is numpy?

NumPy is a Python library mainly used for scientific and numerical computing. Its core feature is the ndarray object, which allows us to store data in one-dimensional or multi-dimensional arrays. These arrays can handle large amounts of data efficiently and all elements usually have the same data type. NumPy also provides fast functions for mathematical and other array operations.

### Numpy Arrays Vs Python Sequences

NumPy arrays have a fixed size when they are created. Unlike Python lists, they cannot be resized directly; changing their size creates a new array.
. All elements in a NumPy array have the same data type, so they generally use the same amount of memory.
. NumPy makes mathematical operations easier and faster when working with large amounts of data, often requiring less code than Python lists.
. Many scientific and mathematical Python libraries use NumPy arrays. They often convert Python lists into NumPy arrays for processing and may also return NumPy arrays as output.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)
# this is a one dimenisonal array

[1 2 3]


In [2]:
a.shape

(3,)

In [3]:
a.ndim

1

In [ ]:
# create a another one dimensional array with 10 elements
b=np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
b.shape

(9,)

In [ ]:
b.ndim

1

In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

In [ ]:
# create a 2d array with shape 3*3
np.array([[1,2,3],[1,2,3],[1,2,3]]).ndim

2

In [ ]:
# create a another 2d array of shape 4*4
np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
#create a another 2d array of 2*3
np.array([[1,2,3],[1,2,3]]).ndim

2

In [ ]:
#create a 3d array with shape 2*2*2
np.array([[[1,2],[1,2]],[[1,2],[1,2]]]).ndim


3

In [ ]:
# create a 3d array with 3*3*3 shape
np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]).ndim

3

# Note
2 means 1d

2*2 means 2d

2*2*2 means 3d

2*2*2*2 means 4d array

In [ ]:
# create a array with a shape 3*3*3

In [ ]:
# create a array with a shape 2*1*2

In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# create with a dtype a int
# dtype
np.array([1,2,3],dtype=int)

array([1, 2, 3])

In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# create a array using a arrange

In [ ]:
x = 5          # integer scalar
y = 3.14       # float scalar
z = True       # boolean scalar


In [7]:
# with reshape
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# your task create a 45 elements array and then reshape it
# with reshape
np.arange(45).reshape(3,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [ ]:
# make a own question and do it

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.54988629, 0.65603589, 0.80160735, 0.14190849],
       [0.05817619, 0.44473108, 0.59812542, 0.45711916],
       [0.67490161, 0.72795099, 0.56062325, 0.853054  ]])

In [ ]:
# np.linspace
np.linspace(-10,10,dtype=int)

array([-10, -10, -10,  -9,  -9,  -8,  -8,  -8,  -7,  -7,  -6,  -6,  -6,
        -5,  -5,  -4,  -4,  -4,  -3,  -3,  -2,  -2,  -2,  -1,  -1,   0,
         0,   1,   1,   1,   2,   2,   3,   3,   3,   4,   4,   5,   5,
         5,   6,   6,   7,   7,   7,   8,   8,   9,   9,  10])

In [ ]:
# np.linspace
np.linspace(-5,5,10,dtype=int)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  5])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a3.ndim

3

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize
a3.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# scalar operations

# arithmetic
a1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1

array([[0.23171919, 0.10037536, 0.07619484],
       [0.30582047, 0.75221749, 0.39101259],
       [0.75367053, 0.47362783, 0.38904145]])

In [ ]:
a1 = np.round(a1*100)
a1

array([[23., 10.,  8.],
       [31., 75., 39.],
       [75., 47., 39.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([35991., 46872., 17892.])

In [ ]:
np.max(a1)

np.float64(75.0)

In [ ]:
np.min(a2)

np.float64(0.0)

In [ ]:
# mean/median/std/var
np.var(a1)

np.float64(530.6913580246915)

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.83177474,  0.27090579,  0.95105465],
       [ 0.95637593, -0.94828214, -0.99177885],
       [-0.40403765, -0.75098725,  0.6569866 ]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[9.74480345e+09, 2.20264658e+04, 2.98095799e+03],
       [2.90488497e+13, 3.73324200e+32, 8.65934004e+16],
       [3.73324200e+32, 2.58131289e+20, 8.65934004e+16]])

### np.ceil() → Ceiling

Definition: Rounds each number UP to the nearest integer.

Always goes toward +∞, no matter what.

In [ ]:
import numpy as np

arr = np.array([1.2, 2.7, -1.5, -2.3])
arr


array([ 1.2,  2.7, -1.5, -2.3])

In [ ]:
np.ceil(arr)

array([ 2.,  3., -1., -2.])

### np.floor() → Floor

Definition: Rounds each number DOWN to the nearest integer.

Always goes toward -∞.

In [ ]:
np.floor(arr)


array([ 1.,  2., -2., -3.])

### np.round() → Round (to nearest)

Definition: Rounds each number to the nearest integer.

If decimal = 0.5 → rounds to nearest even integer (NumPy behavior).

In [ ]:
np.round(arr)


array([ 1.,  3., -2., -2.])

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,0]

4

In [ ]:
a2[1,2]

np.int64(6)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[0,1,0]

np.int64(2)

In [ ]:
### find the elements 7

In [ ]:
# find elements 3

In [ ]:
# whats the output
a3[1,1,0]

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


### Reshaping

In [ ]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])